# Generated by Django 4.2.16 on 2024-10-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="登录账号")),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                ("nickname", models.CharField(max_length=50, verbose_name="昵称")),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="邮箱"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="电话")),
                ("address", models.CharField(max_length=255, verbose_name="地址")),
                (
                    "user_type",
                    models.CharField(
                        choices=[("normal", "普通用户"), ("admin", "管理员")],
                        default="normal",
                        max_length=20,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "addtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
            ],
            options={
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
            },
        ),
    ]
