# Generated by Django 4.2.16 on 2024-10-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_id",
                    models.CharField(default="", max_length=255, verbose_name="商品id"),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                ("score", models.IntegerField(verbose_name="评分")),
                (
                    "comment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论日期"),
                ),
            ],
            options={
                "verbose_name": "商品评论表",
                "verbose_name_plural": "商品评论表",
                "ordering": ["-comment_date"],
            },
        ),
        migrations.CreateModel(
            name="XinXi",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "product_id",
                    models.CharField(default="", max_length=255, verbose_name="商品id"),
                ),
                ("product_name", models.CharField(max_length=255, verbose_name="商品名")),
                (
                    "price",
                    models.CharField(default="", max_length=255, verbose_name="价格"),
                ),
                (
                    "shop",
                    models.CharField(default="", max_length=255, verbose_name="店铺"),
                ),
                (
                    "brand",
                    models.CharField(default="", max_length=255, verbose_name="品牌"),
                ),
                (
                    "img_url",
                    models.CharField(default="", max_length=255, verbose_name="图片"),
                ),
                (
                    "CommentCountStr",
                    models.IntegerField(default=0, max_length=255, verbose_name="总评数"),
                ),
                (
                    "AverageScore",
                    models.CharField(default="", max_length=255, verbose_name="平均得分"),
                ),
                (
                    "GoodCountStr",
                    models.CharField(default="", max_length=255, verbose_name="好评数"),
                ),
                (
                    "DefaultGoodCountStr",
                    models.CharField(default="", max_length=255, verbose_name="默认好评"),
                ),
                (
                    "GoodRate",
                    models.CharField(default="", max_length=255, verbose_name="好评率"),
                ),
                (
                    "AfterCountStr",
                    models.CharField(default="", max_length=255, verbose_name="追评数"),
                ),
                (
                    "VideoCountStr",
                    models.CharField(default="", max_length=255, verbose_name="视频晒单数"),
                ),
                (
                    "PoorCountStr",
                    models.CharField(default="", max_length=255, verbose_name="差评数"),
                ),
                (
                    "GeneralCountStr",
                    models.CharField(default="", max_length=255, verbose_name="中评数"),
                ),
            ],
            options={
                "verbose_name": "商品信息表",
                "verbose_name_plural": "商品信息表",
            },
        ),
    ]
