# Generated by Django 4.2.25 on 2025-11-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_comment_xinxi"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneProduct",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "product_id",
                    models.CharField(default="", max_length=255, verbose_name="商品id"),
                ),
                ("product_name", models.CharField(max_length=255, verbose_name="商品名")),
                (
                    "price",
                    models.CharField(default="", max_length=255, verbose_name="价格"),
                ),
                (
                    "shop",
                    models.CharField(default="", max_length=255, verbose_name="店铺"),
                ),
                (
                    "brand",
                    models.CharField(default="", max_length=255, verbose_name="品牌"),
                ),
                (
                    "img_url",
                    models.CharField(default="", max_length=255, verbose_name="图片"),
                ),
                ("sales", models.IntegerField(default=0, verbose_name="月销量")),
                ("CommentCountStr", models.IntegerField(default=0, verbose_name="总评数")),
                (
                    "AverageScore",
                    models.CharField(default="", max_length=255, verbose_name="平均得分"),
                ),
                (
                    "GoodCountStr",
                    models.CharField(default="", max_length=255, verbose_name="好评数"),
                ),
                (
                    "DefaultGoodCountStr",
                    models.CharField(default="", max_length=255, verbose_name="默认好评"),
                ),
                (
                    "GoodRate",
                    models.CharField(default="", max_length=255, verbose_name="好评率"),
                ),
                (
                    "AfterCountStr",
                    models.CharField(default="", max_length=255, verbose_name="追评数"),
                ),
                (
                    "VideoCountStr",
                    models.CharField(default="", max_length=255, verbose_name="视频晒单数"),
                ),
                (
                    "PoorCountStr",
                    models.CharField(default="", max_length=255, verbose_name="差评数"),
                ),
                (
                    "GeneralCountStr",
                    models.CharField(default="", max_length=255, verbose_name="中评数"),
                ),
            ],
            options={
                "verbose_name": "手机商品",
                "verbose_name_plural": "手机商品",
                "db_table": "simulated_phone_products",
            },
        ),
        migrations.AlterField(
            model_name="xinxi",
            name="CommentCountStr",
            field=models.IntegerField(default=0, verbose_name="总评数"),
        ),
    ]
